RDT_web/RDT_web/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from korisnici import views as korisnik_views
from django.conf import settings
from django.conf.urls.static import static
from galerija import views as galerija_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('novosti/', include('novosti.urls')),
    path('korisnici/', include('korisnici.urls')),
    path('dronovi/', include('dronovi.urls')),
    path('kviz/', include('kviz.urls')),
    path('galerija/', include('galerija.urls')),
    path('', galerija_views.carousel, name='carousel'),
]

#ovo je ovako samo zbog lakse citljivosti, mozes + static(...) dodat iza uglate zagrade u prethodnom redu
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RDT_web/kviz/urls.py
from django.urls import path
from .views import home, rezultati
from .views import (
	KvizListView,
	KvizDetailView,
	KvizCreateView,
	KvizUpdateView,
	KvizDeleteView,
	OdgovorListView,
	OdgovorDetailView,
	OdgovorCreateView,
	OdgovorUpdateView,
	OdgovorDeleteView,
)

app_name='kviz'

urlpatterns = [
    path('', home, name='kviz_home'),
    path('rezultati/', rezultati, name='rezultati'),
    path('pitanja_lista/',KvizListView.as_view(), name='pitanja_lista'),
	path('pitanje_detalji/<int:pk>/', KvizDetailView.as_view(), name='pitanje_detalji'),
	path('pitanje_update/<int:pk>/uredi/',KvizUpdateView.as_view(), name='pitanje_update'),
	path('pitanje_delete/<int:pk>/obrisi/', KvizDeleteView.as_view(), name='pitanje_delete'),
    path('pitanje_add/', KvizCreateView.as_view(), name='pitanje_add'),
    path('odgovori_lista/',OdgovorListView.as_view(), name='odgovori_lista'),
	path('odgovor_detalji/<int:pk>/', OdgovorDetailView.as_view(), name='odgovor_detalji'),
	path('odgovor_update/<int:pk>/uredi/',OdgovorUpdateView.as_view(), name='odgovor_update'),
	path('odgovor_delete/<int:pk>/obrisi/', OdgovorDeleteView.as_view(), name='odgovor_delete'),
    path('odgovor_add/', OdgovorCreateView.as_view(), name='odgovor_add'),
]

RDT_web/novosti/urls.py
from django.urls import path
from . import views
from .views import (
	PostListView, 
	PostDetailView,
	PostCreateView,
	PostUpdateView,
	PostDeleteView,
    ImageDeleteView
	)

urlpatterns = [
    path('', PostListView.as_view(), name='novosti-home'),
    path('clanak/<int:pk>/', PostDetailView.as_view(), name='clanak-detail'),
    path('clanak/novi/', PostCreateView.as_view(), name='clanak-create'),
    path('clanak/<int:pk>/uredi/', PostUpdateView.as_view(), name='clanak-update'),
    path('clanak/<int:pk>/obrisi/', PostDeleteView.as_view(), name='clanak-delete'),
    path('info/', views.info, name='novosti-info'),
    path('pretraga/', views.search, name='pretraga'),
    path('clanak/<int:pk>/slike/', views.clanak_slike, name='clanak-slike'),
    path('slika/<int:pk>/obrisi/', ImageDeleteView.as_view(), name='slika-obrisi'),
]

RDT_web/novosti/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Clanak(models.Model):
	naslov = models.CharField(max_length=100)
	sadrzaj = models.TextField()
	datum_objave = models.DateTimeField(default=timezone.now)
	autor = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.naslov

	def get_absolute_url(self):
		return reverse('clanak-detail', kwargs={'pk': self.pk})

RDT_web/novosti/views.py
from django.shortcuts import render, redirect, reverse
from .models import Clanak
from django.views.generic import (
	ListView,
	DetailView,
	CreateView,
	UpdateView,
	DeleteView
	)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from galerija.models import Image
from django.contrib.auth.decorators import login_required
from galerija.forms import PostImageUploadForm
from django.contrib import messages

# Create your views here.

#ovo je class based view za novosti.html
class PostListView(ListView):
	model = Clanak
	paginate_by = 5
	template_name = 'novosti/novosti.html'

	#ordering = ['-datum_objave'] #ovo iz nekog razloga ne radi kad definiram get_context_data
	#context_object_name = 'posts'

	def get_context_data(self, **kwargs):
		context = super(PostListView, self).get_context_data(**kwargs)

		#pagination mora bit ovako jer inace je overridano paginate_by iz super klase
		p = Paginator(Clanak.objects.all().order_by('-datum_objave'), self.paginate_by)

		context['activate'] = 'novosti'
		context['posts'] = p.page(context['page_obj'].number)
		return context


class PostDetailView(DetailView):
	model = Clanak
	#po defaultu trazi template u obliku: <app>/<model>_<viewtype>.html

	def get_context_data(self, **kwargs):
		context = super(PostDetailView, self).get_context_data(**kwargs)

		context['images'] = Image.objects.filter(clanak=self.kwargs.get('pk'))[:20] #p.page(context['page_obj'].number)
		return context


class PostCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
	model = Clanak
	fields = ['naslov', 'sadrzaj']
	#po defaultu trazi template u obliku: <app>/<model>_<viewtype>.html (za createview viewtype je form)

	def form_valid(self, form):
		form.instance.autor = self.request.user
		return super().form_valid(form)

	def get_context_data(self, **kwargs):
		context = super(PostCreateView, self).get_context_data(**kwargs)
		context['activate'] = 'novi_clanak'
		return context

	def test_func(self):
		usr = self.request.user
		if usr.groups.filter(name='Editors').exists():
			return True
		return False


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Clanak
	fields = ['naslov', 'sadrzaj']
	#po defaultu trazi template u obliku: <app>/<model>_<viewtype>.html (za updateview viewtype je form)

	def get_context_data(self, **kwargs):
		context = super(PostUpdateView, self).get_context_data(**kwargs)
		new_image_form = PostImageUploadForm()
		context['activate'] = 'novi_clanak'
		return context

	def form_valid(self, form):
		form.instance.autor = self.request.user
		return super().form_valid(form)

	def test_func(self):
		clanak = self.get_object()
		usr = self.request.user
		if usr == clanak.autor and usr.groups.filter(name='Editors').exists():
			return True
		return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Clanak
	success_url = '/novosti/'
	#po defaultu trazi template u obliku: <app>/<model>_<viewtype>.html (ovdje je clanak_confirm_delete.html)

	def test_func(self):
		clanak = self.get_object()
		usr = self.request.user
		if usr == clanak.autor and usr.groups.filter(name='Editors').exists():
			return True
		return False



def info(request):
	return render(request, 'novosti/info.html', {'activate': 'info'})


def search(request):
	val = request.GET.get('value')
	usr = User.objects.filter(username__contains=val)
	clanak = Clanak.objects.filter(naslov__contains=val).order_by('-datum_objave')
	clanak |= Clanak.objects.filter(autor__in=usr).order_by('-datum_objave')
	clanak |= Clanak.objects.filter(sadrzaj__contains=val).order_by('-datum_objave')
	page = request.GET.get('page', 1)

	paginator = Paginator(clanak, 5)
	try:
		clanci = paginator.page(page)
	except PageNotAnInteger:
		clanci = paginator.page(1)
	except EmptyPage:
		clanci = paginator.page(paginator.num_pages)

	context = {
		'posts': clanci
	}
	return render(request, 'novosti/search.html', context)


@login_required
def clanak_slike(request, pk):
	usr = request.user
	cl = Clanak.objects.filter(pk=pk).first()
	slike = Image.objects.filter(clanak=cl)

	if usr != cl.autor:
		return redirect('clanak-detail', pk)

	if usr.groups.filter(name='Editors').exists():
		if request.method == 'POST':
			for _file in request.FILES.getlist('image'):
				list = {'image' :_file, }
				form = PostImageUploadForm(request.POST, list)
				if(not _file.name.lower().endswith(('.avi', '.mp4', '.png', '.jpg', 'jpeg'))):
					messages.warning(request, f'Nedozvoljeni format')
					form = PostImageUploadForm()
					break
				if form.is_valid():
					new = form.save(commit=False)
					new.image = form.cleaned_data['image']
					new.clanak = cl
					if(_file.name.lower().endswith(('.avi', 'mp4'))):
						new.slika = False
					new.save()
					form.save_m2m()
					messages.success(request, f'Slika uspjesno dodana')
				else:
					messages.error(request, "Incorrect file type")
			return redirect('clanak-detail', pk)
		else:
			form = PostImageUploadForm()

		context = {
			'slike': slike,
			'form': form,
			'activate': 'image_upload',
		}
		return render(request, 'novosti/slike.html', context)
	else:
		return redirect('login')


class ImageDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Image
	#success_url = '' #promjeni
	#po defaultu trazi template u obliku: <app>/<model>_<viewtype>.html (ovdje je clanak_confirm_delete.html)

	def test_func(self):
		slika = self.get_object()
		clanak = slika.clanak
		usr = self.request.user
		if usr == clanak.autor and usr.groups.filter(name='Editors').exists():
			return True
		return False

	def get_success_url(self, **kwargs):
		return reverse('clanak-slike', kwargs={'pk': self.object.clanak_id})

RDT_web/novosti/templates/novosti/base.html
{% load static %}
{% load group_tags %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

	<!--css za base stranicu-->
	<link rel="stylesheet" type="text/css" href="{% static 'novosti/base.css' %}">

	<title>RDT novosti</title>
</head>
<body>
	<div class="container-fluid">
		<div class="row content">
			<div class="col-md-2 sidenav">
				<div class="sticky-top">
					<p><a href="{% url 'carousel' %}"><img src="{% static 'novosti/LOGO_RDT.png' %}" alt="RDT_logo" style="width:50%;height:auto;" class="img-circle img-responsive logo_img"/></a></p>

					<ul class="nav nav-pills flex-column">
						<li class="nav-item"><a class="nav-link btn btn-light {% if activate == 'novosti' %} active {% endif %}" href="{% url 'novosti-home' %}">Novosti</a></li>
						<li class="nav-item"><a class="nav-link nav-dropdown-toggle btn btn-light {% if activate == 'galerija' %} active {% endif %}" href="{% url 'galerija' %}">Galerija</a>
						<li class="nav-item"><a class="nav-link btn btn-light {% if activate == 'info' %} active {% endif %}" href="{% url 'novosti-info' %}">Info/Kontakti</a></li>
						<li class="nav-item"><a class="nav-link btn btn-light {% if activate == 'team' %} active {% endif %}" href="{% url 'team_list' %}">Clanovi</a></li>
						<li class="nav-item"><a class="nav-link btn btn-light {% if activate == 'dronovi' %} active {% endif %}" href="{% url 'dronovi-home' %}">Dronovi</a></li>

						<!--
						<li class="nav-item"><a class="nav-link" href="#">Dronovi</a></li>
						<li class="nav-item"><a class="nav-link" href="#">Galerija</a></li>
						<li class="nav-item"><a class="nav-link" href="#">Kviz</a></li>
						<li class="nav-item"><a class="nav-link" href="#">Ucenje</a></li>
						-->
						{% if user.is_authenticated %}
						<li class="nav-item"><a class="nav-link btn btn-light {% if activate == 'kalendar' %} active {% endif %}" href="{% url 'kalendar_leta_default' %}">Kalendar Leta</a></li>
							<li class="nav-item"><a class="nav-link btn btn-light {% if activate == 'kviz' %} active {% endif %}" href="{% url 'kviz:kviz_home' %}">Kviz</a></li>
							<li class="nav-item"><a class="nav-link btn btn-outline-info {% if activate == 'profil' %} active {% endif %}" href="{% url 'profil' user.username %}">Profil</a></li>


							{% if request.user|has_group:"Editors" %}
								<li class="nav-item"><a class="nav-link btn btn-light text-info{% if activate == 'upload' %} active {% endif %}" href="{% url 'galerija-upload' %}">Dodaj Slike</a></li>
								<li class="nav-item"><a class="nav-link btn btn-light text-info{% if activate == 'novi_clanak' %} active {% endif %}" href="{% url 'clanak-create' %}">Novi clanak</a></li>
								<li class="nav-item"><a class="nav-link btn btn-light text-info{% if activate == 'novi_dron' %} active {% endif %}" href="{% url 'dron-create' %}">Novi dron</a></li>
								<li class="nav-item"><a class="nav-link btn btn-light text-info{% if activate == 'kviz_lista' %} active {% endif %}" href="{% url 'kviz:pitanja_lista' %}">Uredivanje Kviza</a></li>
							{% endif %}

							<li class="nav-item"><a class="nav-link btn btn-info" href="{% url 'logout' %}">Odjavi se</a></li>
						{% else %}
							<li class="nav-item"><a class="nav-link btn btn-outline-info" href="{% url 'login' %}">Prijavi se</a></li>
							<li class="nav-item"><a class="nav-link btn btn-info {% if activate == 'registracija' %} active {% endif %}" href="{% url 'registracija' %}">Registriraj se</a></li>
						{% endif %}
					</ul><br>
					<form method="GET" action="{% url 'pretraga' %}">
						{% csrf_token %}
					<div class="input-group">
						<input type="text" class="form-control" placeholder="Search . . ." name="value">
						<span class="input-group-btn">
							<button class="btn btn-secondary" type="submit">

								<!--search ikona-->
								<img src="{% static 'novosti/web-serch_w.png' %}" style="width:18px; height:18px;" alt="GO!" class="img-circle img-responsive"/>
							</button>
						</span>
					</div>
					</form>

				</div>
			</div>

			<div class="col-sm-10 background">
				{% if messages %}
					{% for message in messages %}
						<div class="alert alert-{{ message.tags }}">
							{{ message }}
						</div>
					{% endfor %}
				{% endif %}

				{% block content %}{% endblock content %}

			</div>
		</div>
	</div>

	<footer>
	Footer text
	</footer>

  </body>
</body>
</html>

RDT_web/novosti/templates/novosti/clanak_confirm_delete.html
{% extends "novosti/base.html" %}

{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %} <!--form security, django requires-->
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Obrisi Clanak</legend>
				<h2>Jeste li sigurni da zelite obrisati clanak "{{ object.naslov }}"</h2>
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-danger" type="submit">Obrisi</button>
				<a class="btn btn-outline-secondary" href="{% url 'clanak-detail' object.id %}">Odustani</a>
			</div>
		</form>
	</div>

{% endblock content %}

RDT_web/novosti/templates/novosti/clanak_detail.html
{% extends "novosti/base.html" %}
{% load static %}
{% block content %}
	<link rel="stylesheet" type="text/css" href="{% static 'galerija/galerija.css'%}">
	<article class="media content-section">
		<img class="rounded-circle article-img" src="{{ object.autor.profil.slika.url }}">

		<div class="media-body">
		   	<div class="article-metadata">
		      	<a class="mr-2" href="{% url 'profil' object.autor.username %}">{{ object.autor }}</a>
			 	<small class="text-muted">{{ object.datum_objave|date:"d. F, Y." }}</small>
			 	{% if object.autor == user %}
			 		<div>
						<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'clanak-update' object.id %}">Uredi</a>
						<a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'clanak-delete' object.id %}">Obrisi</a>
					</div>
			 	{% endif %}
			</div>
			<h2 class="article-title">{{ object.naslov }}</h2>
		    <p class="article-content">{{ object.sadrzaj }}</p>
		</div>
	</article>
	{% if images %}
	<div class="content-section" align="center">
    <div id="myModal" class="modal" onclick="this.style.display='none'">
	</div>
    <div id="myModal1" class="modal">
	</div>
	{% for image in images %}
		{% if image.slika %}
			{% if image.image %}
		        <img id="{{image.image.url}}"class="col-md-4 col-lg-1 img-thumbnail" src="{{image.image.url}}" style="max-width: 150px; height: 150px">


				<script>
				// Get the modal
				var modal = document.getElementById('myModal');

				var img = document.getElementById('{{image.image.url}}');
				var modalImg = document.getElementById("myModal");
				img.onclick = function(){
					myModal.innerHTML += "<span id='close1' class='close'>&times;</span><img src='{{image.image.url}}' class='modal-content' id='img01'>";
					//Ovdje mijenjas sto zelis da ti ispise ispod slika
					myModal.innerHTML += "<div class='card' style='width: 50%'>{%if image.clanak.naslov%}<p>Clanak = {{image.clanak.naslov}}</p>{%endif%} {%if image.autor.profil%}<p>Autor = {{image.autor.profil.ime}} {{image.autor.profil.prezime}}</p>{%endif%}{%if image.dron.naziv%}<p>Dron = {{image.dron.naziv}}</p>{%endif%}</div>";
					modal.style.display = "block";
					var span = document.getElementsByClassName("close")[0];

					// When the user clicks on <span> (x), close the modal
					span.onclick = function() {
						myModal.innerHTML = "";
						modal.style.display = "none";
					}
					modalImg.onclick = function() {
						myModal.innerHTML = "";
						modal.style.display = "none";
					}
				}

				// Get the <span> element that closes the modal
				</script>
			{% endif %}
		{% else %}
			{% if image.image %}
				<video id="{{image.image.url}}" class="col-md-4 col-lg-1 img-thumbnail" style="max-width:150px; position:relative;top:50%">
			        <source src="{{image.image.url}}" type="video/mp4">
		        </video>

				<script>
				// Get the image and insert it inside the modal - use its "alt" text as a caption
				var vid = document.getElementById('{{image.image.url}}');
				console.log(vid.id);
				vid.onclick = function(){

					source = document.getElementById('{{image.image.url}}');
					myModal1.innerHTML += "<span id='close1' class='close'>&times;</span><video class='modal-content' id='vid01' controls><source src=" + source.id + "></video>";
					//Ovdje uredujes sto zelis da ti ispise ispod videa
					myModal1.innerHTML += "<div class='card' style='width: 50%'>{%if image.clanak.naslov%}<p>Clanak = {{image.clanak.naslov}}</p>{%endif%} {%if image.autor.profil%}<p>Autor = {{image.autor.profil.ime}} {{image.autor.profil.prezime}}</p>{%endif%}{%if image.dron.naziv%}<p>Dron = {{image.dron.naziv}}</p>{%endif%}</div>";
					myModal1.style.display = "block";

					// Get the <span> element that closes the modal
					var span = document.getElementById("close1");
					// When the user clicks on <span> (x), close the modal
					span.onmouseup = function() {
					  myModal1.style.display = "none";
					  document.getElementById("vid01").pause();
					  myModal1.innerHTML = "";
					}
				}
				</script>
			{% endif %}
		{% endif %}
	{% endfor %}
	</div>
	{% endif %}
{% endblock content %}

RDT_web/novosti/templates/novosti/clanak_form.html
{% extends "novosti/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %} <!--form security, django requires-->
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Clanak</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				{% if object %}
					<a class="btn btn-secondary " href="{% url 'clanak-slike' object.id %}">Uredi slike</a>
				{% endif %}
				<button class="btn btn-outline-info" type="submit">Objavi</button>
			</div>
		</form>
	</div>

{% endblock content %}

RDT_web/novosti/templates/novosti/info.html
{% extends "novosti/base.html" %}

{% block content %}
	<div class="content-section">
		<h2>RiTeh Drone Team - Info</h2><br>
		<h3>Motivacija</h3>
		<p>Entuzijazam 
i želja za razvojem letjelica i tehnologija vezanih uz iste: 
računalni vid, autonomija, GPS sustav, radio komunikacija...</p>
		<h3>Ciljevi</h3>
		<p><ul>
			<li>Omogućiti snimanje događaja iz zraka za potrebe Sveučilišta u Rijeci</li>

			<li>Razvoj novih tehnologija vezanih za bespilotne letjelice te znastvenog napretka u području bespilotnih letjelica sa četiri i više motora te jedrilica</li>

			<li>Ostvarivanje odnosa sa službama za spašavanje Republike Hrvatske te uspostava zajednickih projekata</li>

			<li>Izrada znanstvenih radova te prisustvovanje konferencijama </li>

			<li>Doprinos zajednici i širenje suradnje fakulteta i industrije</li>

			<li>Mogućnost korištenja letjelica i u komercijalne svrhe</li>
		</ul></p>

		<h3>Djelovanje RiTeh Drone Team-a</h3>
		<p><ul>
			<li>Rad Riteh Drone Team-a je projektno vođen, što znači da njegov rad neće biti fokusiran samo na jedan specifični projekt istovremeno</li>

			<li>Svaki projekt će imati vođu projekta koji je zadužen za njegovu provedbu u skladu sa postavljenim ciljevima i rokovima</li>

			<li>Ciljevi i vremenski rokovi definiraju se na početku projekta, te ovise o dogovoru između članova koji rade na tom projektu</li>

			<li>Odabir projekata i postavljanje ciljeva biti će ostvareno dogovorom i raspravom svih članova Riteh Drone Team-a </li>

			<li>Projekti će biti vođeni putem online servisa kako bi u svakom trenutku bio moguć uvid u stanje projekta</li>
		</ul></p>

		<h3>Moguci projekti</h3>
		<p><ul>
			<li>Projekt razvoja autonomije letjelice koji obuhvaća aktivnosti poput sletanja na vodu i automatskog punjenja baterije</li>

			<li>Razvoj First Person View upravljanja letjelice</li>

			<li>Prenošenje i dostava manjih paketa na području grada Rijeke putem GPS navođenja</li>

			<li>3D mapiranje prostora uz pomoć lidar kamera </li>

			<li>Fotogrametrija</li>

			<li>Detekcija anomalija (požari...) na nedostupnim područjima</li>

			<li>Omogućiti 3D pogled iz letjelice uz pomoć Virtual Reality tehnologije i headtracking-a</li>
		</ul></p>
	</div>
{% endblock content %}

RDT_web/novosti/templates/novosti/mail_template.html
<!DOCTYPE html>
<html>
<head>
	<title>Mail</title>
</head>
<body>
	<p>Novi clanak je objavljen na RDT stranici, <a href="http://localhost:8000/novosti/">Pogledaj!</a></p>
</body>
</html>

RDT_web/novosti/templates/novosti/novosti.html
{% extends "novosti/base.html" %}

{% block content %}
	{% for post in posts %}

	<article class="media content-section">
		<img class="rounded-circle article-img" src="{{ post.autor.profil.slika.url }}">

		<div class="media-body">
		   	<div class="article-metadata">
		      	<a class="mr-2" href="{% url 'profil' post.autor.username %}">{{ post.autor }}</a>
			 	<small class="text-muted">{{ post.datum_objave|date:"d. F, Y." }}</small>
			</div>
			<h2><a class="article-title" href="{% url 'clanak-detail' post.id %}">{{ post.naslov }}</a></h2>
		    <p class="article-content">{{ post.sadrzaj|truncatewords:30 }}</p>
		</div>
	</article>
	{% endfor %}
	
	{% if is_paginated %}

		{% if page_obj.has_previous %}
			<a class="btn btn-outline-dark mb-4" href="?page=1">Prva</a>
			<a class="btn btn-outline-dark mb-4" href="?page={{ page_obj.previous_page_number }}">Prethodna</a>
		{% endif %}

		{% for num in page_obj.paginator.page_range %}
			{% if page_obj.number == num %}
				<a class="btn btn-dark mb-4" href="?page={{ num }}">{{ num }}</a>
			{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
				<a class="btn btn-outline-dark mb-4" href="?page={{ num }}">{{ num }}</a>
			{% endif %}
		{% endfor %}

		{% if page_obj.has_next %}
			<a class="btn btn-outline-dark mb-4" href="?page={{ page_obj.next_page_number }}">Sljedeca</a>
			<a class="btn btn-outline-dark mb-4" href="?page={{ page_obj.paginator.num_pages }}">Zadnja</a>
		{% endif %}

	{% endif %}

{% endblock content %}

RDT_web/novosti/templates/novosti/slike.html
{% extends "novosti/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
	<div class="content-section">
		<div class="mt-4">
			<form method="post" enctype="multipart/form-data">
				{% csrf_token %}
				<h5>Dodaj slike:</h5>
				{{ form|crispy }}
				<input type="submit" value="Dodaj" class="btn btn-outline-info">
			</form>
		</div>
	</div>

	<div class="content-section">
		<h3>Uredi slike</h3>
		<div>
			{% for image in slike %}
				{% if image.slika %}
			        <div class="container-custom mt-1 mb-1">
			        	<img src="{{image.image.url}}" style="width:100%">
			        	<a class="btn btn-danger btn-custom" href="{% url 'slika-obrisi' image.pk %}">Delete</a>
			        </div>
			    {% else %}
			     <div class="container-custom mt-1 mb-1">
			    	<video id="{{image.image.url}}" style="width:100%;">
			        <source src="{{image.image.url}}" type="video/mp4">
		        </video>
		        	<a class="btn btn-danger btn-custom" href="{% url 'slika-obrisi' image.pk %}">Delete</a>
		        </div>
				{% endif %}
			{% endfor %}
		</div>
	</div>
{% endblock content %}