RDT_web/RDT_web/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from korisnici import views as korisnik_views
from django.conf import settings
from django.conf.urls.static import static
from galerija import views as galerija_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('novosti/', include('novosti.urls')),
    path('korisnici/', include('korisnici.urls')),
    path('dronovi/', include('dronovi.urls')),
    path('kviz/', include('kviz.urls')),
    path('galerija/', include('galerija.urls')),
    path('', galerija_views.carousel, name='carousel'),
]

#ovo je ovako samo zbog lakse citljivosti, mozes + static(...) dodat iza uglate zagrade u prethodnom redu
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RDT_web/kviz/urls.py
from django.urls import path
from .views import home, rezultati
from .views import (
	KvizListView,
	KvizDetailView,
	KvizCreateView,
	KvizUpdateView,
	KvizDeleteView,
	OdgovorListView,
	OdgovorDetailView,
	OdgovorCreateView,
	OdgovorUpdateView,
	OdgovorDeleteView,
)

app_name='kviz'

urlpatterns = [
    path('', home, name='kviz_home'),
    path('rezultati/', rezultati, name='rezultati'),
    path('pitanja_lista/',KvizListView.as_view(), name='pitanja_lista'),
	path('pitanje_detalji/<int:pk>/', KvizDetailView.as_view(), name='pitanje_detalji'),
	path('pitanje_update/<int:pk>/uredi/',KvizUpdateView.as_view(), name='pitanje_update'),
	path('pitanje_delete/<int:pk>/obrisi/', KvizDeleteView.as_view(), name='pitanje_delete'),
    path('pitanje_add/', KvizCreateView.as_view(), name='pitanje_add'),
    path('odgovori_lista/',OdgovorListView.as_view(), name='odgovori_lista'),
	path('odgovor_detalji/<int:pk>/', OdgovorDetailView.as_view(), name='odgovor_detalji'),
	path('odgovor_update/<int:pk>/uredi/',OdgovorUpdateView.as_view(), name='odgovor_update'),
	path('odgovor_delete/<int:pk>/obrisi/', OdgovorDeleteView.as_view(), name='odgovor_delete'),
    path('odgovor_add/', OdgovorCreateView.as_view(), name='odgovor_add'),
]

RDT_web/kviz/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Pitanja(models.Model):
    text_pitanja = models.TextField()

    def __str__(self):
        return self.text_pitanja

    def get_absolute_url(self):
        return reverse('kviz:pitanja_lista')


class Odgovori(models.Model):
    text_odgovora = models.TextField()
    tocan = models.BooleanField(default=0)
    pitanje = models.ForeignKey(Pitanja, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.text_odgovora}'

    def get_absolute_url(self):
        return reverse('kviz:odgovori_lista')

    def clean(self):
    	if self.tocan and Odgovori.objects.filter(pitanje=self.pitanje).filter(tocan=self.tocan).exists():
            raise ValidationError('Vec postoji tocan odgovor na to pitanje')


class Rezultat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    datum_rjesavanja = models.DateTimeField(default=timezone.now)
    rezultat = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f'{self.user} - rezultat: {self.datum_rjesavanja}'

RDT_web/kviz/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Pitanja, Odgovori, Rezultat
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Pitanja, Odgovori
from django.views.generic import (
	ListView,
	DetailView,
	CreateView,
	UpdateView,
	DeleteView
	)

@login_required
def home(request):
    br_pitanja = 20
    br_pitanja_limit = Pitanja.objects.count()
    if br_pitanja >= br_pitanja_limit:
        br_pitanja = br_pitanja_limit
    sva_pitanja = Pitanja.objects.order_by('?')[:br_pitanja]
    context = {
        'lista_pitanja': sva_pitanja,
        'activation': 'kviz'
    }
    return render(request, 'kviz/home.html', context)


@login_required
def rezultati(request):
    score = 0
    brpit = 0
    if request.method == 'POST':
        pitanja = Pitanja.objects.all()

        for p in pitanja:
            odgovor = Odgovori.objects.filter(pitanje=p, tocan=True)
            odgovor = odgovor.first()
            odgval = request.POST.get('odg' + str(p.id), 0)
            if odgval == str(odgovor.id):
                score += 1
            brpit += 1

    percent = score/brpit * 100
    noviRez = Rezultat(user=request.user,rezultat=percent)
    previous_page = request.META.get('HTTP_REFERER')
    if previous_page != request.build_absolute_uri('/kviz/'):
        return redirect('kviz:kviz_home')

    noviRez.save()
    context = {
        'score': score,
        'brpit': brpit
    }
    return render(request, 'kviz/rezultati.html', context)

class KvizListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
	model = Pitanja
	template_name = 'kviz/pitanja_lista.html'
	paginate_by = 13

	def get_context_data(self, **kwargs):
		context = super(KvizListView, self).get_context_data(**kwargs)
		pitanja = Pitanja.objects.all()

		page = self.request.GET.get('page', 1)

		#pagination mora bit ovako jer inace je overridano paginate_by iz super klase
		paginator_pit = Paginator(pitanja, self.paginate_by)

		try:
			context['pitanja'] = paginator_pit.page(page)
		except PageNotAnInteger:
			context['pitanja'] = paginator_pit.page(1)
		except EmptyPage:
			context['pitanja'] = paginator_pit.page(paginator_pit.num_pages)

		context['activate'] = 'kviz_lista'
		return context

	def test_func(self):
		usr = self.request.user
		if usr.groups.filter(name='Editors').exists():
			return True
		return False


class KvizDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
	model = Pitanja


	def get_context_data(self, **kwargs):
		context = super(KvizDetailView, self).get_context_data(**kwargs)
		context['activate'] = 'kviz_lista'
		return context

	def test_func(self):
		usr = self.request.user
		if usr.groups.filter(name='Editors').exists():
			return True
		return False


class KvizCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
	model = Pitanja
	fields = ['text_pitanja']

	def get_context_data(self, **kwargs):
		context = super(KvizCreateView, self).get_context_data(**kwargs)
		context['activate'] = 'kviz_lista'
		return context

	def test_func(self):
		usr = self.request.user
		if usr.groups.filter(name='Editors').exists():
			return True
		return False


class KvizUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Pitanja
	fields = ['text_pitanja']

	def get_context_data(self, **kwargs):
		context = super(KvizUpdateView, self).get_context_data(**kwargs)
		context['activate'] = 'kviz_lista'
		return context

	def test_func(self):
		usr = self.request.user
		if usr.groups.filter(name='Editors').exists():
			return True
		return False


class KvizDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Pitanja
	success_url = '/kviz/pitanja_lista/'

	def get_context_data(self, **kwargs):
		context = super(KvizDeleteView, self).get_context_data(**kwargs)
		context['activate'] = 'kviz_lista'
		return context


	def test_func(self):
		usr = self.request.user
		if usr.groups.filter(name='Editors').exists():
			return True
		return False

class OdgovorDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
	model = Odgovori

	def get_context_data(self, **kwargs):
		context = super(OdgovorDetailView, self).get_context_data(**kwargs)
		context['activate'] = 'kviz_lista'
		return context

	def test_func(self):
		usr = self.request.user
		if usr.groups.filter(name='Editors').exists():
			return True
		return False


class OdgovorCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
	model = Odgovori
	fields = ['text_odgovora', 'tocan', 'pitanje']

	def get_context_data(self, **kwargs):
		context = super(OdgovorCreateView, self).get_context_data(**kwargs)
		context['activate'] = 'kviz_lista'
		return context

	def test_func(self):
		usr = self.request.user
		if usr.groups.filter(name='Editors').exists():
			return True
		return False


class OdgovorUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Odgovori
	fields = ['text_odgovora', 'tocan', 'pitanje']

	def get_context_data(self, **kwargs):
		context = super(OdgovorUpdateView, self).get_context_data(**kwargs)
		context['activate'] = 'kviz_lista'
		return context

	def test_func(self):
		usr = self.request.user
		if usr.groups.filter(name='Editors').exists():
			return True
		return False


class OdgovorDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Odgovori
	success_url = '/kviz/odgovori_lista/'

	def get_context_data(self, **kwargs):
		context = super(OdgovorDeleteView, self).get_context_data(**kwargs)
		context['activate'] = 'kviz_lista'
		return context

	def test_func(self):
		usr = self.request.user
		if usr.groups.filter(name='Editors').exists():
			return True
		return False

class OdgovorListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
	model = Odgovori
	template_name = 'kviz/odgovori_lista.html'
	paginate_by = 13

	def get_context_data(self, **kwargs):
		context = super(OdgovorListView, self).get_context_data(**kwargs)
		odgovori = Odgovori.objects.all()

		page = self.request.GET.get('page', 1)

		#pagination mora bit ovako jer inace je overridano paginate_by iz super klase
		paginator_odg = Paginator(odgovori, self.paginate_by)

		try:
			context['odgovori'] = paginator_odg.page(page);
		except PageNotAnInteger:
			context['odgovori'] = paginator_odg.page(1);
		except EmptyPage:
			context['odgovori'] = paginator_odg.page(paginator_odg.num_pages);

		context['activate'] = 'kviz_lista'
		return context

	def test_func(self):
		usr = self.request.user
		if usr.groups.filter(name='Editors').exists():
			return True
		return False

RDT_web/kviz/templates/kviz/detalji.html
<h1>{{pitanje.text_pitanja}}</h1>
{%if error_message%}
<p><strong>{{error_message}}</strong></p>
{%endif%}

<form class="" action="{%url 'kviz:pitnaje_odg' pitanje.id%}" method="post">
  {%csrf_token%}
  {%for odg in pitanje.odgovori_set.all%}
    <input type="radio" name="odg" value="{{odg.id}}" id="odg{{forloop.counter}}">
    <label for="odg{{forloop.counter}}">{{odg.text_odgovora}}</label>
    <br>
  {% endfor %}
  <input type="submit" name="" value="odgovori">
</form>

RDT_web/kviz/templates/kviz/home.html
{% extends "novosti/base.html" %}

{% block content %}

  <p id="cnt"></p>

  <script>
  // Set the date we're counting down to
  var countDownDate = new Date().getTime()+1230000;

  // Update the count down every 1 second
  var x = setInterval(function() {

    // Get todays date and time
    var now = new Date().getTime();

    // Find the distance between now and the count down date
    var distance = countDownDate - now;

    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);

    // Output the result in an element with id="cnt"
    document.getElementById("cnt").innerHTML =/*days + " " + hours + " " +*/ minutes + "m " + seconds + "s ";

    // If the count down is over, write some text
    if (distance < 0) {
      clearInterval(x);
      document.getElementById("cnt").innerHTML = "KVIZ JE ZAVRSIO";
      document.getElementById("kviz").submit()
    }
  }, 1000);
  </script>

<div class="content-section">
  <h2>Priprema za teorijski ispit</h2>

  <form id="kviz" method="POST" action="{% url 'kviz:rezultati' %} " autocomplete="off">
    {%csrf_token%}

    <hr>
    <div class="container">
    <div id="accordion">
      {%for pitanje in lista_pitanja%}
      <div class="card">
        <div class="card-header bg-light">
          <a class="card-link text-dark" data-toggle="collapse" href="#link{{pitanje.id}}">
            <h3>{{ forloop.counter }}. {{ pitanje.text_pitanja }}</h3>
          </a>
        </div>
        <div id="link{{pitanje.id}}" class="collapse" data-parent="#accordion">
          <div class="card-body">
            {%for odg in pitanje.odgovori_set.all%}
            <input type="radio" name="odg{{pitanje.id}}" value="{{odg.id}}" id="odg{{odg.id}}">
            <label for="odg1">{{odg.text_odgovora}}</label><br>
            {% endfor %}
          </div>
        </div>
      </div>
      <hr>
      {%endfor%}
    </div>
    </div>
    <input class="btn btn-outline-info" type="submit" name="" value="Odgovori">
  </form>
</div>

{% endblock content %}

RDT_web/kviz/templates/kviz/kviz_lista.html
{% extends "novosti/base.html" %}
{% load group_tags %}
{% block content %}
{% if request.user|has_group:"Editors" %}
<div id="content-main" class="container">
  <a href="{%url 'kviz:pitanje_add'%}" class="btn btn-info">Novo Pitanje </a>
  <a href="{%url 'kviz:odgovor_add'%}" class="btn btn-info">Novi Odgovor </a>
</div>
<hr>
<div class="content-section">
  <ul class="nav nav-pills nav-fill mt-2">
    <li class="nav-item">
      <a href="#pills_pitanja" class="nav-link {%if not odg%} active {%endif%}" id="pills_pitanja_tab" data-toggle="pill" role="tab" aria-controls="pills_pitanja" aria-selected="true">Pitanja</a>
    </li>
    <li class="nav-item">
      <a href="#pills_odg" class="nav-link show {%if odg%} active {%endif%}" id="pills_odg_tab" data-toggle="pill" role="tab" aria-controls="pills_odg" aria-selected="true">Odgovori</a>
    </li>
  </ul>
  <div class="tab-content" id="tab_content">
    <div class="tab-pane fade show {%if not odg%} active {%endif%}" id="pills_pitanja" role="tabpanel" aria-labelledby="pills_pitanja_tab">
      {%for pitanje in pitanja%}
        <hr>
        <div class="media media-body pt-4">
          <h4><a href="{% url 'kviz:pitanje_detalji' pitanje.id%}" class="text-dark">{{pitanje.text_pitanja}}</a></h4>
        </div>
        <hr>
      {%endfor%}

      {% if pitanja.has_previous %}
        <a class="btn btn-outline-dark mb-4" href="?page=1">Prva</a>
        <a class="btn btn-outline-dark mb-4" href="?page={{ pitanja.previous_page_number}}">Prethodna</a>
      {% endif %}

      {% for num in pitanja.paginator.page_range %}
        {% if pitanja.number == num %}
          <a class="btn btn-dark mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > pitanja.number|add:'-3' and num < pitanja.number|add:'-3' %}
          <a class="btn btn-outline-dark mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor%}

      {% if pitanja.has_next %}
        <a class="btn btn-outline-dark mb-4" href="?page={{ pitanja.next_page_number }}">Sljedeca</a>
        <a class="btn btn-outline-dark mb-4" href="?page={{ pitanja.paginator.num_pages }}">Zadnja</a>
      {% endif %}
    </div>

    <div class="tab-pane fade show {%if odg%} active {%endif%}" id="pills_odg" role="tabpanel" aria-labelledby="pills_odg_tab">
      {% for odgovor in odgovori %}
      <hr>
        <div class="media-body pt-4 media">
          <h4><a href="{% url 'kviz:odgovor_detalji' odgovor.id %}"  class="text-dark">{{ odgovor.text_odgovora }}</a></h4>
        </div>
      <hr>
      {% endfor %}

      {% if odgovori.has_previous %}
        <a class="btn btn-outline-dark mb-4" href="?page=1&odg=1">Prva</a>
        <a class="btn btn-outline-dark mb-4" href="?page={{ odgovori.previous_page_number }}&odg=1">Prethodna</a>
      {% endif %}

      {% for num in odgovori.paginator.page_range %}
        {% if odgovori.number == num %}
          <a class="btn btn-dark mb-4" href="?page={{ num }}&odg=1">{{ num }}</a>
        {% elif num > odgovori.number|add:'-3' and num < odgovori.number|add:'3' %}
          <a class="btn btn-outline-dark mb-4" href="?page={{ num }}&odg=1">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if odgovori.has_next %}
        <a class="btn btn-outline-dark mb-4" href="?page={{ odgovori.next_page_number }}&odg=1">Sljedeca</a>
        <a class="btn btn-outline-dark mb-4" href="?page={{ odgovori.paginator.num_pages }}&odg=1">Zadnja</a>
      {% endif %}
    </div>
  </div>
</div>
{% endif %}
{% endblock content %}

RDT_web/kviz/templates/kviz/odgovori_confirm_delete.html
{% extends "novosti/base.html" %}

{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %} <!--form security, django requires-->
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Obrisi Odgovor</legend>
				<h2>Jeste li sigurni da zelite obrisati Odgovor: "{{ object.text_odgovora }}" na pitnaje: "{{object.pitanje}}"</h2>
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-danger" type="submit">Obrisi </button>
				<a class="btn btn-outline-secondary" href="{% url 'kviz:odgovor_detalji' object.id %}">Odustani</a>
			</div>
		</form>
	</div>

{% endblock content %}

RDT_web/kviz/templates/kviz/odgovori_detail.html
{% extends "novosti/base.html" %}
{% load group_tags %}
{% block content %}

	<div class="content-section media">
	   	<div class="media-body pt-4">
	   		{% if request.user|has_group:"Editors" %}
				<div>
					<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'kviz:odgovor_update' object.id %}">Uredi</a>
					<a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'kviz:odgovor_delete' object.id %}">Obrisi</a>
				</div>
			{% endif %}
	   		<h2 class="account-heading article-title">{{ object.text_odgovora }}</h2>
          <p class="text-secondary">{{ object.tocan }}</p>
          <p class="text-secondary">{{ object.pitanje }}</p>
	   	</div>
	</div>

{% endblock content %}

RDT_web/kviz/templates/kviz/odgovori_form.html
{% extends "novosti/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
	<div class="content-section">
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %} <!--form security, django requires-->
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Odovor</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Potvrdi</button>
			</div>
		</form>
	</div>

{% endblock content %}

RDT_web/kviz/templates/kviz/odgovori_lista.html
{% extends "novosti/base.html" %}
{% load group_tags %}
{% block content %}

{% if request.user|has_group:"Editors" %}
  <div class="container">
		<div id="content-main" class="float-left">
			<a href="{%url 'kviz:pitanje_add'%}" class="btn btn-info">Novo Pitnaje </a>
			<a href="{%url 'kviz:odgovor_add'%}" class="btn btn-info">Novi Odgovor </a>
		</div>
		<div id="content-main" class="float-right">
			<a href="{%url 'kviz:pitanja_lista'%}" class="btn btn-info">Pitanja </a>
		</div>
    <br><br>
  </div>
		<hr>
		<div class="content-section">
	{% for odgovor in odgovori %}
	    	<div class="media-body pt-4 media">
	      		<a class="account-heading article-title" href="{% url 'kviz:odgovor_detalji' odgovor.id %}">{{ odgovor.text_odgovora }}</a>
				</div>
	{% endfor %}
	  	</div>

	{% if is_paginated %}

		{% if odgovori.has_previous %}
			<a class="btn btn-outline-dark mb-4" href="?page=1">Prva</a>
			<a class="btn btn-outline-dark mb-4" href="?page={{ odgovori.previous_page_number }}">Prethodna</a>
		{% endif %}

		{% for num in odgovori.paginator.page_range %}
			{% if odgovori.number == num %}
				<a class="btn btn-dark mb-4" href="?page={{ num }}">{{ num }}</a>
			{% elif num > odgovori.number|add:'-3' and num < odgovori.number|add:'3' %}
				<a class="btn btn-outline-dark mb-4" href="?page={{ num }}">{{ num }}</a>
			{% endif %}
		{% endfor %}

		{% if odgovori.has_next %}
			<a class="btn btn-outline-dark mb-4" href="?page={{ odgovori.next_page_number }}">Sljedeca</a>
			<a class="btn btn-outline-dark mb-4" href="?page={{ odgovori.paginator.num_pages }}">Zadnja</a>
		{% endif %}

	{% endif %}
{% endif %}
{% endblock content %}

RDT_web/kviz/templates/kviz/pitanja_confirm_delete.html
{% extends "novosti/base.html" %}

{% block content %}
	<div class="content-section">
		<form method="POST">
			{% csrf_token %} <!--form security, django requires-->
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Obrisi Pitnaje</legend>
				<h2>Jeste li sigurni da zelite obrisati pitnaje: "{{ object.text_pitanja }}"</h2>
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-danger" type="submit">Obrisi </button>
				<a class="btn btn-outline-secondary" href="{% url 'kviz:pitanje_detalji' object.id %}">Odustani</a>
			</div>
		</form>
	</div>

{% endblock content %}

RDT_web/kviz/templates/kviz/pitanja_detail.html
{% extends "novosti/base.html" %}
{% load group_tags %}
{% block content %}

	<div class="content-section media">
	   	<div class="media-body pt-4">
	   		{% if request.user|has_group:"Editors" %}
				<div>
					<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'kviz:pitanje_update' object.id %}">Uredi</a>
					<a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'kviz:pitanje_delete' object.id %}">Obrisi</a>
				</div>
			{% endif %}
	   		<h2 class="account-heading article-title">{{ object.text_pitanja }}</h2>
        {%for odg in object.odgovori_set.all%}
          <p class="text-secondary">{{forloop.counter}}. {{ odg.text_odgovora }}</p>
        {% endfor %}
	   	</div>
	</div>

{% endblock content %}

RDT_web/kviz/templates/kviz/pitanja_form.html
{% extends "novosti/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
	<div class="content-section">
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %} <!--form security, django requires-->
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Pitanje</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Potvrdi</button>
			</div>
		</form>
	</div>

{% endblock content %}

RDT_web/kviz/templates/kviz/pitanja_lista.html
{% extends "novosti/base.html" %}
{% load group_tags %}
{% block content %}

{% if request.user|has_group:"Editors" %}
	<div class="container">
		<div id="content-main" class="float-left">
			<a href="{%url 'kviz:pitanje_add'%}" class="btn btn-info">Novo Pitnaje </a>
			<a href="{%url 'kviz:odgovor_add'%}" class="btn btn-info">Novi Odgovor </a>
		</div>
		<div id="content-main" class="float-right">
			<a href="{%url 'kviz:odgovori_lista'%}" class="btn btn-info">Odgovori </a>
		</div>
		<br><br>
	</div>
		<hr>
		<div class="content-section">
	{% for pitanje in pitanja %}
	    	<div class="media-body pt-4 media">
	      		<a class="account-heading article-title" href="{% url 'kviz:pitanje_detalji' pitanje.id %}">{{ pitanje.text_pitanja }}</a>
				</div>
	{% endfor %}
	  	</div>

	{% if is_paginated %}

		{% if pitanja.has_previous %}
			<a class="btn btn-outline-dark mb-4" href="?page=1">Prva</a>
			<a class="btn btn-outline-dark mb-4" href="?page={{ pitanja.previous_page_number }}">Prethodna</a>
		{% endif %}

		{% for num in pitanja.paginator.page_range %}
			{% if pitanja.number == num %}
				<a class="btn btn-dark mb-4" href="?page={{ num }}">{{ num }}</a>
			{% elif num > pitanja.number|add:'-3' and num < pitanja.number|add:'3' %}
				<a class="btn btn-outline-dark mb-4" href="?page={{ num }}">{{ num }}</a>
			{% endif %}
		{% endfor %}

		{% if pitnaja.has_next %}
			<a class="btn btn-outline-dark mb-4" href="?page={{ pitnaja.next_page_number }}">Sljedeca</a>
			<a class="btn btn-outline-dark mb-4" href="?page={{ pitanja.paginator.num_pages }}">Zadnja</a>
		{% endif %}

	{% endif %}
{% endif %}
{% endblock content %}

RDT_web/kviz/templates/kviz/rezultati.html
{% extends "novosti/base.html" %}
{% block content %}

<div class="content-section">
	<h3>Vas rezultat je:</h3>
	<h4 class="text-success">{{ score }}/{{ brpit }}</h4>
	<p><a class="btn btn-secondary btn-sm" href="{% url 'kviz:kviz_home' %}">Ponovno rjesi kviz</a></p>
</div>
{% endblock content%}